---
- name: add official nginx repository
  yum:
    name: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
    state: present

- name: NGINX | Installing NGINX
  yum:
    name: nginx
    state: latest
