---
#www.yml : playbook for web servers
- hosts: www
  remote_user: root 
#  sudo: yes
  pre_tasks:
    - shell: echo 'I":" Beginning to configure web server..'
  roles:
    - nginx
  post_tasks:
    - shell: echo 'I":" Done configuring nginx web server...'
